services:
  mysql:
    image: mysql:8.4.2
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=redis
      - MYSQL_USER=redis
      - MYSQL_PASSWORD=redis
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysql", "-u", "redis", "-predis", "-e", "SELECT 1 FROM information_schema.tables WHERE table_schema = 'redis'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      demo:
        ipv4_address: 172.32.0.2
  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    cap_add:
      - SYS_RESOURCE
    expose:
      - 6379
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true
    networks:
      demo:
        ipv4_address: 172.32.0.3
  app:
    build:
      context: ./kinexis-demo
      dockerfile: Dockerfile
    image: foogaro/kinexis-demo
    container_name: app
    hostname: app
    restart: unless-stopped
    depends_on:
      - mysql
    cap_add:
      - SYS_RESOURCE
    expose:
      - 8080
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    networks:
      demo:
        ipv4_address: 172.32.0.4

  mongo:
    image: mongo:8.0.10-noble
    container_name: mongodb
    hostname: mongodb
#    volumes:
#      - ./mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#      - mongodb-data:/data/db/
#      - mongodb-log:/var/log/mongodb/
#    env_file:
#      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    ports:
      - "27017:27017"
    networks:
      demo:
        ipv4_address: 172.32.0.5

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'admin'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'admin'
    ports:
      - 8081:8081
    networks:
      demo:
        ipv4_address: 172.32.0.6

networks:
  demo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1
