spring.application.name=kinexis-demo-mongodb
server.port=${SERVER_PORT:8082}

spring.mongodb.uri=${MONGODB_URI:mongodb://kinexis:kinexis@localhost:27017/kinexis?authSource=admin}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6381}
spring.data.redis.username=${REDIS_USERNAME:}
spring.data.redis.password=${REDIS_PASSWORD:}

kinexis.stream.listener.pending.max-attempts=3
kinexis.stream.listener.pending.max-retention=120000
kinexis.stream.listener.pending.batch-size=50
kinexis.stream.listener.pending.fixed-delay=60000

logging.level.com.foogaro.kinexis=DEBUG
logging.level.com.foogaro.kinexis.demo.mongodb=DEBUG
