spring.application.name=kinexis-demo-cassandra
server.port=${SERVER_PORT:8084}

spring.cassandra.contact-points=${CASSANDRA_CONTACT_POINTS:localhost}
spring.cassandra.port=${CASSANDRA_PORT:9042}
spring.cassandra.local-datacenter=${CASSANDRA_LOCAL_DATACENTER:datacenter1}
spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE:kinexis}
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6383}
spring.data.redis.username=${REDIS_USERNAME:}
spring.data.redis.password=${REDIS_PASSWORD:}

kinexis.stream.listener.pending.max-attempts=3
kinexis.stream.listener.pending.max-retention=120000
kinexis.stream.listener.pending.batch-size=50
kinexis.stream.listener.pending.fixed-delay=60000

logging.level.com.foogaro.kinexis=DEBUG
logging.level.com.foogaro.kinexis.demo.cassandra=DEBUG
