spring.application.name=kinexis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.username=
spring.data.redis.password=


# SQL datasource settings
kinexis.datasource.mysql.url=${MYSQL_URL:jdbc:mysql://mysql:3306/redis}
kinexis.datasource.mysql.username=${MYSQL_USER:redis}
kinexis.datasource.mysql.password=${MYSQL_PASSWORD:redis}
kinexis.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
kinexis.datasource.mysql.hikari.connection-timeout=1000
kinexis.datasource.mysql.hikari.pool-name=kinexis-mysql
kinexis.datasource.mysql.hikari.maximum-pool-size=20

kinexis.datasource.postgres.url=${POSTGRES_URL:jdbc:postgresql://postgres:5432/kinexis}
kinexis.datasource.postgres.username=${POSTGRES_USER:kinexis}
kinexis.datasource.postgres.password=${POSTGRES_PASSWORD:kinexis}
kinexis.datasource.postgres.driver-class-name=org.postgresql.Driver
kinexis.datasource.postgres.hikari.connection-timeout=1000
kinexis.datasource.postgres.hikari.pool-name=kinexis-postgres
kinexis.datasource.postgres.hikari.maximum-pool-size=20

kinexis.datasource.sqlserver.url=${SQLSERVER_URL:jdbc:sqlserver://sqlserver:1433;databaseName=master;encrypt=false;trustServerCertificate=true}
kinexis.datasource.sqlserver.username=${SQLSERVER_USER:sa}
kinexis.datasource.sqlserver.password=${SQLSERVER_PASSWORD:Kinexis_password123}
kinexis.datasource.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
kinexis.datasource.sqlserver.hikari.connection-timeout=1000
kinexis.datasource.sqlserver.hikari.pool-name=kinexis-sqlserver
kinexis.datasource.sqlserver.hikari.maximum-pool-size=20

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.jackson.default-property-inclusion=always

# Optional: logging settings
#logging.level.root=DEBUG
logging.level.com.foogaro.redis=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Kinexis
kinexis.stream.listener.pending.max-attempts=3
kinexis.stream.listener.pending.max-retention=120000
kinexis.stream.listener.pending.batch-size=50
kinexis.stream.listener.pending.fixed-delay=60000

# Espone gli endpoint delle metriche
management.endpoints.web.exposure.include=metrics,prometheus
# Aggiunge tag comuni a tutte le metriche
management.metrics.tags.application=${spring.application.name}
# Abilita le metriche di base
management.metrics.enable.all=true


# MongoDB
spring.data.mongodb.uri=mongodb://admin:admin@mongodb:27017/mydb?authSource=admin
